default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgresql
  password: DBPA55
  pool: 5

development:
  <<: *default
  database: summitplan_development

test:
  <<: *default
  database: summitplan_test