# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb52ce7b7f74f8ef9c782bf06f431a4903c1c9e58483a47c0ff19cbeaf62bcfedce889471cdb8eadb4063122c1d54fe842fc6fda5d343d1d5668831a1b88629d

test:
  secret_key_base: e42e964553bc5e7fada465da7cd6e200e27e3a0d68e8c327336b5147841ffe7f1e1cd1ea9be70b43baa9818ccfb26f72b46e7cce025fb15b44cfc05cbff8b748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
