fourteeners_attributes=[
	{name:"Antero", surname:"Mount", elevation_in_feet:14269, rank:10, location_lat:38.674088, location_long:-106.246201, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:2400, round_trip_distance_in_miles:7, no_4wd_additional_elevation_in_feet: 2800, no_4wd_additional_distance_in_miles:9, route_name:"West Slopes", trailhead_name:"Baldwin Gulch", trailhead_lat:38.71002, trailhead_long:-106.29163, four_x_four_required:2, additional_info_url:"https://www.14ers.com/route.php?route=ante1&peak=Mt.+Antero
"},
	{name:"Belford", surname:"Mount", elevation_in_feet:14197, rank:18, location_lat:38.960575, location_long:-106.360832, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:1, elevation_gain_in_feet:4500, round_trip_distance_in_miles:8, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northwest Ridge", trailhead_name:"Missouri Gulch", trailhead_lat:38.99807, trailhead_long:-106.37508, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=belf1&peak=Mt.+Belford+and+Mt.+Oxford
"},
	{name:"Bierdstadt", surname:"Mount", elevation_in_feet:14060, rank:38, location_lat:39.582638, location_long:-105.66861, forest:"Arapaho", range:"Pike", classification:2.3, exposure:1, elevation_gain_in_feet:2850, round_trip_distance_in_miles:7, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"West Slopes", trailhead_name:"Guanella Pass", trailhead_lat:39.59688, trailhead_long:-105.71003, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=bier1&peak=Mt.+Bierstadt
"},
	{name:"Bross", surname:"Mount", elevation_in_feet:14172, rank:22, location_lat:39.33506, location_long:-106.107376, forest:"Pike", range:"Mosquito", classification:1.3, exposure:1, elevation_gain_in_feet:2900, round_trip_distance_in_miles:9, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slopes from Mineral Park Mine", trailhead_name:"Mineral Park", trailhead_lat:39.31814, trailhead_long:-106.08448, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=bros1&peak=Mt.+Bross
"},
	{name:"Cameron", surname:"Mount", elevation_in_feet:14286, rank:?, location_lat:39.351391, location_long:-106.111404, forest:"Pike", range:"Mosquito", classification:2.3, exposure:1, elevation_gain_in_feet:, round_trip_distance_in_miles:, no_4wd_additional_elevation_in_feet: , no_4wd_additional_distance_in_miles:, route_name:"", trailhead_name:"", trailhead_lat:, trailhead_long:, four_x_four_required:, additional_info_url:"
"},
	{name:"Columbia", surname:"Mount", elevation_in_feet:14073, rank:35, location_lat:38.903957, location_long:-106.297485, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4250, round_trip_distance_in_miles:11.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"West Slopes", trailhead_name:"North Cottonwood Creek", trailhead_lat:38.87057, trailhead_long:-106.2658, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=colu2&peak=Mt.+Harvard+and+Mt.+Columbia
"},
	{name:"Democrat", surname:"Mount", elevation_in_feet:14148, rank:28, location_lat:39.339542, location_long:-106.139946, forest:"Pike", range:"Mosquito", classification:2.3, exposure:1, elevation_gain_in_feet:2150, round_trip_distance_in_miles:4, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slopes", trailhead_name:"Kite Lake", trailhead_lat:39.32758, trailhead_long:-106.12928, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=demo1&peak=Mt.+Democrat
"},
	{name:"Elbert", surname:"Mount", elevation_in_feet:14433, rank:1, location_lat:39.118075, location_long:-106.445417, forest:"San Isabel", range:"Sawatch", classification:1.3, exposure:1, elevation_gain_in_feet:4700, round_trip_distance_in_miles:9.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge", trailhead_name:"Mt Elbert ", trailhead_lat:39.15216, trailhead_long:-106.41235, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=elbe1&peak=Mt.+Elbert
"},
	{name:"Eolus", surname:"Mount", elevation_in_feet:14083, rank:32, location_lat:37.621948, location_long:-107.622498, forest:"San Juan", range:"San Juan", classification:3.3, exposure:4, elevation_gain_in_feet:3000, round_trip_distance_in_miles:5, no_4wd_additional_elevation_in_feet: 3100, no_4wd_additional_distance_in_miles:12, route_name:"Northeast Ridge ", trailhead_name:"Needleton", trailhead_lat:37.63333, trailhead_long:-107.69278, four_x_four_required:TRAIN, additional_info_url:"https://www.14ers.com/route.php?route=eolu3&peak=Mt.+Eolus%2C+Windom+Peak%2C+and+Sunlight+Peak
"},
	{name:"Evans", surname:"Mount", elevation_in_feet:14264, rank:14, location_lat:39.58836, location_long:-105.643333, forest:"Arapahoe", range:"Front", classification:2.3, exposure:2, elevation_gain_in_feet:2000, round_trip_distance_in_miles:4.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"West Ridge via Mt. Spalding", trailhead_name:"Evans/Summit Lake", trailhead_lat:39.59882, trailhead_long:-105.64039, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=evan2&peak=Mt.+Evans
"},
	{name:"Harvard", surname:"Mount", elevation_in_feet:14420, rank:3, location_lat:39.924328, location_long:-106.320618, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4600, round_trip_distance_in_miles:14, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"South Slopes", trailhead_name:"North Cottonwood Creek ", trailhead_lat:38.87057, trailhead_long:-106.2658, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=harv1&peak=Mt.+Harvard+and+Mt.+Columbia
"},
	{name:"Lincoln", surname:"Mount", elevation_in_feet:14286, rank:8, location_lat:39.351391, location_long:-106.111404, forest:"Pike", range:"Mosquito", classification:2.3, exposure:1, elevation_gain_in_feet:2600, round_trip_distance_in_miles:6, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"West Ridge", trailhead_name:"Kite Lake", trailhead_lat:39.32758, trailhead_long:-106.12928, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=linc1&peak=Mt.+Lincoln
"},
	{name:"Lindsey", surname:"Mount", elevation_in_feet:14042, rank:43, location_lat:37.583801, location_long:-105.444763, forest:"San Isabel", range:"Sangre de Cristo", classification:3, exposure:3, elevation_gain_in_feet:3500, round_trip_distance_in_miles:8.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"North Face", trailhead_name:"Huerfano/Lily Lake", trailhead_lat:37.62361, trailhead_long:-105.47278, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=lind1&peak=Mt.+Lindsey
"},
	{name:"Massive", surname:"Mount", elevation_in_feet:14421, rank:2, location_lat:39.187298, location_long:-106.475548, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4500, round_trip_distance_in_miles:14.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slopes", trailhead_name:"Mt Massive ", trailhead_lat:39.15177, trailhead_long:-106.41918, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=mass1&peak=Mt.+Massive
"},
	{name:"Oxford", surname:"Mount", elevation_in_feet:14153, rank:26, location_lat:38.96468, location_long:-106.338432, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:5800, round_trip_distance_in_miles:11, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"via Mt Belford", trailhead_name:"Missouri Gulch", trailhead_lat:38.99807, trailhead_long:-106.37508, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=oxfo2&peak=Mt.+Belford+and+Mt.+Oxford
"},
	{name:"Princeton", surname:"Mount", elevation_in_feet:14197, rank:20, location_lat:38.749062, location_long:-106.242432, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:3200, round_trip_distance_in_miles:6.5, no_4wd_additional_elevation_in_feet: 2200, no_4wd_additional_distance_in_miles:6.75, route_name:"East Slopes", trailhead_name:"Mt Princeton Road", trailhead_lat:38.73994, trailhead_long:-106.17558, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=prin1&peak=Mt.+Princeton
"},
	{name:"Shavano", surname:"Mount", elevation_in_feet:14229, rank:17, location_lat:38.619083, location_long:-106.239296, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4600, round_trip_distance_in_miles:9.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slopes", trailhead_name:"Shavano/Tabeguache", trailhead_lat:38.59863, trailhead_long:-106.19722, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=shav1&peak=Mt.+Shavano+and+Tabeguache+Peak
"},
	{name:"Sherman", surname:"Mount", elevation_in_feet:14036, rank:45, location_lat:39.225006, location_long:-106.169945, forest:"Pike", range:"Mosquito", classification:2.3, exposure:2, elevation_gain_in_feet:2100, round_trip_distance_in_miles:5.25, no_4wd_additional_elevation_in_feet: 3100, no_4wd_additional_distance_in_miles:10.5, route_name:"Southwest Ridge via Fourmile Creek", trailhead_name:"Fourmile Creek", trailhead_lat:39.20575, trailhead_long:-106.1622, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=sher1&peak=Mt.+Sherman
"},
	{name:"Sneffels", surname:"Mount", elevation_in_feet:14150, rank:27, location_lat:38.003605, location_long:-107.792229, forest:"Uncompahgre", range:"San Juan", classification:3, exposure:3, elevation_gain_in_feet:1700, round_trip_distance_in_miles:2.5, no_4wd_additional_elevation_in_feet: 1200, no_4wd_additional_distance_in_miles:3.5, route_name:"via Yankee Boy Basin", trailhead_name:"Yankee Boy Basin", trailhead_lat:37.995, trailhead_long:-107.78472, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=snef1&peak=Mt.+Sneffels
"},
	{name:"Wilson", surname:"Mount", elevation_in_feet:14246, rank:16, location_lat:37.83931, location_long:-107.99157, forest:"San Juan", range:"San Juan", classification:4.3, exposure:4, elevation_gain_in_feet:3200, round_trip_distance_in_miles:6.5, no_4wd_additional_elevation_in_feet: 2100, no_4wd_additional_distance_in_miles:4.5, route_name:"North Slopes", trailhead_name:"Navajo Lake", trailhead_lat:37.80339, trailhead_long:-108.06378, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/php14ers/trailheadsview.php?thparm=sj03
"},
	{name:"Yale", surname:"Mount", elevation_in_feet:14196, rank:21, location_lat:38.844051, location_long:-106.313965, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4300, round_trip_distance_in_miles:9.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Southwest Slopes", trailhead_name:"Denny Creek", trailhead_lat:38.815, trailhead_long:-106.33444, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=yale1&peak=Mt.+Yale
"},
	{name:"Holy Cross", surname:"Mount of the ", elevation_in_feet:14005, rank:51, location_lat:39.466713, location_long:-106.481766, forest:"White River", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:5600, round_trip_distance_in_miles:12, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"North Ridge", trailhead_name:"Half Moon (Tigiwon) ", trailhead_lat:39.50054, trailhead_long:-106.43318, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=holy1&peak=Mt.+of+the+Holy+Cross
"},
	{name:"Missouri", surname:"Mountain", elevation_in_feet:14067, rank:36, location_lat:38.947559, location_long:-106.378471, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:3, elevation_gain_in_feet:4500, round_trip_distance_in_miles:10.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northwest Ridge via Missouri Gulch", trailhead_name:"Missouri Gulch", trailhead_lat:38.99807, trailhead_long:-106.37508, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=miss1&peak=Missouri+Mountain
"},
	{name:"Snowmass", surname:"Mountain", elevation_in_feet:14092, rank:31, location_lat:39.118809, location_long:-107.066528, forest:"White River", range:"Elk", classification:3.3, exposure:3, elevation_gain_in_feet:5800, round_trip_distance_in_miles:22, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slope", trailhead_name:"Snowmass Creek", trailhead_lat:39.20016, trailhead_long:-106.99414, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=snow1&peak=Snowmass+Mountain
"},
	{name:"Crestone", surname:"Needle", elevation_in_feet:14197, rank:19, location_lat:37.964737, location_long:-105.576683, forest:"San Isabel", range:"Sangre de Cristo", classification:3.3, exposure:4, elevation_gain_in_feet:4400, round_trip_distance_in_miles:12, no_4wd_additional_elevation_in_feet: 1150, no_4wd_additional_distance_in_miles:6, route_name:"South Face", trailhead_name:"South Colony Lakes", trailhead_lat:37.97611, trailhead_long:-105.50651, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=cnee1&peak=Crestone+Peak+and+Crestone+Needle
"},
	{name:"Blanca", surname:"Peak", elevation_in_feet:14345, rank:4, location_lat:37.577473, location_long:-105.485443, forest:"Rio Grande", range:"Sangre de Cristo", classification:2.6, exposure:2, elevation_gain_in_feet:2700, round_trip_distance_in_miles:6, no_4wd_additional_elevation_in_feet: 3800, no_4wd_additional_distance_in_miles:9, route_name:"Northwest Ridge ", trailhead_name:"Lake Como", trailhead_lat:37.53861, trailhead_long:-105.57611, four_x_four_required:3, additional_info_url:"https://www.14ers.com/route.php?route=blan1&peak=Blanca%2C+Ellingwood+and+Little+Bear
"},
	{name:"Capitol", surname:"Peak", elevation_in_feet:14130, rank:29, location_lat:39.150166, location_long:-107.083221, forest:"White River", range:"Elk", classification:4.3, exposure:4, elevation_gain_in_feet:5300, round_trip_distance_in_miles:17, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge from Capitol Lake", trailhead_name:"Capitol Creek", trailhead_lat:39.23422, trailhead_long:-107.07952, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=capi1&peak=Capitol+Peak
"},
	{name:"Castle", surname:"Peak", elevation_in_feet:14265, rank:12, location_lat:39.009647, location_long:-106.86144, forest:"White River", range:"Elk", classification:2.6, exposure:3, elevation_gain_in_feet:3100, round_trip_distance_in_miles:7, no_4wd_additional_elevation_in_feet: 1500, no_4wd_additional_distance_in_miles:6.5, route_name:"Northeast Ridge", trailhead_name:"Castle Creek", trailhead_lat:39.0289, trailhead_long:-106.80801, four_x_four_required:2, additional_info_url:"https://www.14ers.com/route.php?route=cast1&peak=Castle+Peak+and+Conundrum+Peak
"},
	{name:"Conundrum", surname:"Peak", elevation_in_feet:14060, rank:?, location_lat:39.01563, location_long:-106.86294, forest:"White River", range:"Elk", classification:2.6, exposure:3, elevation_gain_in_feet:3350, round_trip_distance_in_miles:8, no_4wd_additional_elevation_in_feet: 1500, no_4wd_additional_distance_in_miles:6.5, route_name:"Castle & Conundrum Combo", trailhead_name:"Castle Creek", trailhead_lat:39.0289, trailhead_long:-106.80801, four_x_four_required:2, additional_info_url:"https://www.14ers.com/route.php?route=cast4&peak=Castle+Peak+and+Conundrum+Peak
"},
	{name:"Crestone", surname:"Peak", elevation_in_feet:14294, rank:7, location_lat:37.966972, location_long:-105.585304, forest:"San Isabel", range:"Sangre de Cristo", classification:3.3, exposure:3, elevation_gain_in_feet:5700, round_trip_distance_in_miles:14, no_4wd_additional_elevation_in_feet: 1150, no_4wd_additional_distance_in_miles:6, route_name:"South Face", trailhead_name:"South Colony Lakes", trailhead_lat:37.97611, trailhead_long:-105.50651, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=cpea2&peak=Crestone+Peak+and+Crestone+Needle
"},
	{name:"Culebra", surname:"Peak", elevation_in_feet:14047, rank:41, location_lat:37.122173, location_long:-105.185593, forest:"San Juan", range:"Sangre de Cristo", classification:2.3, exposure:2, elevation_gain_in_feet:2700, round_trip_distance_in_miles:5, no_4wd_additional_elevation_in_feet: 2750, no_4wd_additional_distance_in_miles:9, route_name:"Northwest Ridge", trailhead_name:"Culebra", trailhead_lat:37.15, trailhead_long:-105.2925, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=cule1&peak=Culebra+Peak
"},
	{name:"El Diente", surname:"Peak", elevation_in_feet:14159, rank:?, location_lat:37.839275, location_long:-108.005219, forest:"San Juan", range:"San Juan", classification:3.3, exposure:3, elevation_gain_in_feet:3200, round_trip_distance_in_miles:3, no_4wd_additional_elevation_in_feet: 3300, no_4wd_additional_distance_in_miles:9, route_name:"North Slopes", trailhead_name:"Navajo Lake", trailhead_lat:37.80339, trailhead_long:-108.06378, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=eldi3&peak=Mt.+Wilson%2C+Wilson+Peak%2C+and+El+Diente+Peak
"},
	{name:"Grays", surname:"Peak", elevation_in_feet:14270, rank:9, location_lat:39.63382, location_long:-105.81752, forest:"Arapaho", range:"Front", classification:1.3, exposure:1, elevation_gain_in_feet:3000, round_trip_distance_in_miles:8, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slopes", trailhead_name:"Grays Peak", trailhead_lat:39.66087, trailhead_long:-105.78462, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=gray1&peak=Grays+Peak+and+Torreys+Peak
"},
	{name:"Handies", surname:"Peak", elevation_in_feet:14048, rank:40, location_lat:37.913021, location_long:-107.504478, forest:"Uncompahgre", range:"San Juan", classification:1.3, exposure:1, elevation_gain_in_feet:2500, round_trip_distance_in_miles:5.5, no_4wd_additional_elevation_in_feet: 2800, no_4wd_additional_distance_in_miles:2, route_name:"Southwest Slopes", trailhead_name:"American Basin", trailhead_lat:37.92028, trailhead_long:-107.51639, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=hand1&peak=Handies+Peak
"},
	{name:"Humboldt", surname:"Peak", elevation_in_feet:14064, rank:37, location_lat:37.976105, location_long:-105.555351, forest:"San Isabel", range:"Sangre de Cristo", classification:2.3, exposure:2, elevation_gain_in_feet:4200, round_trip_distance_in_miles:11, no_4wd_additional_elevation_in_feet: 1150, no_4wd_additional_distance_in_miles:5.5, route_name:"West Ridge", trailhead_name:"South Colony Lakes", trailhead_lat:37.97611, trailhead_long:-105.50651, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=humb1&peak=Humboldt+Peak
"},
	{name:"Huron", surname:"Peak", elevation_in_feet:14003, rank:52, location_lat:38.945423, location_long:-106.438126, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:3500, round_trip_distance_in_miles:6.5, no_4wd_additional_elevation_in_feet: 300, no_4wd_additional_distance_in_miles:4.25, route_name:"Northwest Slopes", trailhead_name:"Clear Creek/South Winfield", trailhead_lat:38.96039, trailhead_long:-106.46091, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=huro1&peak=Huron+Peak
"},
	{name:"Kit Carson", surname:"Peak", elevation_in_feet:14165, rank:23, location_lat:37.979759, location_long:-105.602562, forest:"Rio Grande", range:"Sangre de Cristo", classification:3, exposure:3, elevation_gain_in_feet:6250, round_trip_distance_in_miles:14.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"via Challenger Point", trailhead_name:"Willow Creek", trailhead_lat:37.98889, trailhead_long:-105.66278, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=kitc2&peak=Kit+Carson+Peak+and+Challenger+Point
"},
	{name:"La Plata ", surname:"Peak", elevation_in_feet:14336, rank:5, location_lat:39.029251, location_long:-106.473145, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:4500, round_trip_distance_in_miles:9.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northwest Ridge ", trailhead_name:"La Plata Peak", trailhead_lat:39.06788, trailhead_long:-106.50515, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=lapl1&peak=La+Plata+Peak
"},
	{name:"Little Bear ", surname:"Peak", elevation_in_feet:14037, rank:44, location_lat:37.566624, location_long:-105.497162, forest:"Rio Grande", range:"Sangre de Cristo", classification:4.3, exposure:4, elevation_gain_in_feet:2300, round_trip_distance_in_miles:3.5, no_4wd_additional_elevation_in_feet: 3900, no_4wd_additional_distance_in_miles:11.5, route_name:"West Ridge and Southwest Face", trailhead_name:"Lake Como ", trailhead_lat:37.53861, trailhead_long:-105.57611, four_x_four_required:3, additional_info_url:"https://www.14ers.com/route.php?route=litt6&peak=Blanca%2C+Ellingwood+and+Little+Bear
"},
	{name:"Longs", surname:"Peak", elevation_in_feet:14255, rank:15, location_lat:40.254902, location_long:-105.615738, forest:"Rocky Mountain", range:"Front", classification:3.3, exposure:3, elevation_gain_in_feet:5100, round_trip_distance_in_miles:14.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Keyhole Route", trailhead_name:"Longs Peak", trailhead_lat:40.27223, trailhead_long:-105.55679, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=long1&peak=Longs+Peak
"},
	{name:"Maroon", surname:"Peak", elevation_in_feet:14156, rank:24, location_lat:39.070713, location_long:-106.989113, forest:"White River", range:"Elk", classification:3.3, exposure:4, elevation_gain_in_feet:4800, round_trip_distance_in_miles:11.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"South Ridge", trailhead_name:"Maroon Lake", trailhead_lat:39.09862, trailhead_long:-106.94064, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=maro1&peak=The+Maroon+Bells
"},
	{name:"North Maroon", surname:"Peak", elevation_in_feet:14014, rank:?, location_lat:39.076077, location_long:-106.987267, forest:"White River", range:"Elk ", classification:4.3, exposure:4, elevation_gain_in_feet:4500, round_trip_distance_in_miles:9.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge", trailhead_name:"Maroon Lake", trailhead_lat:39.09862, trailhead_long:-106.94064, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=nmar2&peak=The+Maroon+Bells
"},
	{name:"Pikes", surname:"Peak", elevation_in_feet:14110, rank:30, location_lat:38.840542, location_long:-105.044357, forest:"Pike", range:"Front", classification:1.3, exposure:1, elevation_gain_in_feet:7500, round_trip_distance_in_miles:26, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Slope", trailhead_name:"Barr Trail", trailhead_lat:38.854767, trailhead_long:-104.949492, four_x_four_required:0, additional_info_url:"https://www.14ers.com/routelist.php?peak=Pikes+Peak
"},
	{name:"Pyramid", surname:"Peak", elevation_in_feet:14018, rank:47, location_lat:39.071545, location_long:-106.950188, forest:"White River", range:"Elk", classification:4.3, exposure:4, elevation_gain_in_feet:4500, round_trip_distance_in_miles:8.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge", trailhead_name:"Maroon Lake", trailhead_lat:39.09862, trailhead_long:-106.94064, four_x_four_required:0, additional_info_url:"https://www.14ers.com/route.php?route=pyra1&peak=Pyramid+Peak
"},
	{name:"Quandary", surname:"Peak", elevation_in_feet:14265, rank:13, location_lat:39.397236, location_long:-106.10643, forest:"White River", range:"Tenmile", classification:1.3, exposure:1, elevation_gain_in_feet:3450, round_trip_distance_in_miles:6.75, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"East Ridge", trailhead_name:"Quandary", trailhead_lat:39.3849, trailhead_long:-106.06178, four_x_four_required:0.5, additional_info_url:"https://www.14ers.com/route.php?route=quan1&peak=Quandary+Peak
"},
	{name:"Redcloud", surname:"Peak", elevation_in_feet:14034, rank:46, location_lat:37.94088, location_long:-107.421654, forest:"San Juan", range:"San Juan", classification:2.3, exposure:2, elevation_gain_in_feet:3700, round_trip_distance_in_miles:9, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge", trailhead_name:"Silver Creek/Grizzly Gulch ", trailhead_lat:37.93694, trailhead_long:-107.46083, four_x_four_required:1.51, additional_info_url:"https://www.14ers.com/route.php?route=redc1&peak=Redcloud+Peak+and+Sunshine+Peak
"},
	{name:"San Luis", surname:"Peak", elevation_in_feet:14014, rank:50, location_lat:37.986897, location_long:-106.931389, forest:"Gunnison", range:"San Juan", classification:1.3, exposure:0, elevation_gain_in_feet:3600, round_trip_distance_in_miles:13.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Northeast Ridge", trailhead_name:"Stewart Creek", trailhead_lat:38.0246, trailhead_long:-106.84124, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=sanl1&peak=San+Luis+Peak
"},
	{name:"Sunlight", surname:"Peak", elevation_in_feet:14059, rank:39, location_lat:37.627285, location_long:-107.595894, forest:"San Juan", range:"San Juan", classification:4.3, exposure:5, elevation_gain_in_feet:3000, round_trip_distance_in_miles:5, no_4wd_additional_elevation_in_feet: 3000, no_4wd_additional_distance_in_miles:12, route_name:"South Face", trailhead_name:"Needleton", trailhead_lat:37.63333, trailhead_long:-107.69278, four_x_four_required:TRAIN, additional_info_url:"https://www.14ers.com/route.php?route=sunl2&peak=Mt.+Eolus%2C+Windom+Peak%2C+and+Sunlight+Peak
"},
	{name:"Sunshine", surname:"Peak", elevation_in_feet:14001, rank:53, location_lat:37.922604, location_long:-107.425606, forest:"San Juan", range:"San Juan", classification:2.3, exposure:2, elevation_gain_in_feet:4800, round_trip_distance_in_miles:12.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"via Red Cloud Peak", trailhead_name:"Silver Creek/Grizzly Gulch ", trailhead_lat:37.93694, trailhead_long:-107.46083, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=suns2&peak=Redcloud+Peak+and+Sunshine+Peak
"},
	{name:"Tabeguache", surname:"Peak", elevation_in_feet:14155, rank:25, location_lat:38.625622, location_long:-106.25071, forest:"San Isabel", range:"Sawatch", classification:2.3, exposure:2, elevation_gain_in_feet:5600, round_trip_distance_in_miles:11.25, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"via Mt. Shavano", trailhead_name:"Shavano/Tabeguache", trailhead_lat:38.59863, trailhead_long:-106.19722, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=tabe3w&peak=Mt.+Shavano+and+Tabeguache+Peak
"},
	{name:"Torreys", surname:"Peak", elevation_in_feet:14267, rank:11, location_lat:39.642742, location_long:-105.821259, forest:"Arapaho", range:"Front", classification:2.3, exposure:1, elevation_gain_in_feet:3000, round_trip_distance_in_miles:8, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"South Slopes", trailhead_name:"Grays Peak", trailhead_lat:39.66087, trailhead_long:-105.78462, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=torr2&peak=Grays+Peak+and+Torreys+Peak
"},
	{name:"Uncompahgre", surname:"Peak", elevation_in_feet:14309, rank:6, location_lat:38.071507, location_long:-107.462166, forest:"Uncompahgre", range:"San Juan", classification:2.3, exposure:2, elevation_gain_in_feet:3000, round_trip_distance_in_miles:7.5, no_4wd_additional_elevation_in_feet: 2505, no_4wd_additional_distance_in_miles:8, route_name:"South Ridge", trailhead_name:"Nellie Creek ", trailhead_lat:38.006209, trailhead_long:-107.42158, four_x_four_required:2, additional_info_url:"https://www.14ers.com/route.php?route=unco1&peak=Uncompahgre+Peak
"},
	{name:"Wetterhorn", surname:"Peak", elevation_in_feet:14015, rank:49, location_lat:38.06593, location_long:-107.510834, forest:"Uncompahgre", range:"San Juan", classification:3.3, exposure:4, elevation_gain_in_feet:3300, round_trip_distance_in_miles:7, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"Southeast Ridge", trailhead_name:"Matterhorn Creek", trailhead_lat:38.02962, trailhead_long:-107.49102, four_x_four_required:2, additional_info_url:"https://www.14ers.com/route.php?route=wett1&peak=Wetterhorn+Peak
"},
	{name:"Wilson", surname:"Peak", elevation_in_feet:14017, rank:48, location_lat:37.859913, location_long:-107.984795, forest:"San Juan", range:"San Juan", classification:3.3, exposure:4, elevation_gain_in_feet:3000, round_trip_distance_in_miles:7, no_4wd_additional_elevation_in_feet: 2000, no_4wd_additional_distance_in_miles:9, route_name:"Southwest Ridge ", trailhead_name:"Rock of Ages ", trailhead_lat:37.88296, trailhead_long:-108.01848, four_x_four_required:1.5, additional_info_url:"https://www.14ers.com/route.php?route=wils1&peak=Mt.+Wilson%2C+Wilson+Peak%2C+and+El+Diente+Peak
"},
	{name:"Windom", surname:"Peak", elevation_in_feet:14082, rank:33, location_lat:37.621235, location_long:-107.591774, forest:"San Juan", range:"San Juan", classification:2.6, exposure:3, elevation_gain_in_feet:3000, round_trip_distance_in_miles:5, no_4wd_additional_elevation_in_feet: 3000, no_4wd_additional_distance_in_miles:12, route_name:"West Ridge", trailhead_name:"Needleton", trailhead_lat:37.63333, trailhead_long:-107.69278, four_x_four_required:TRAIN, additional_info_url:"https://www.14ers.com/route.php?route=wind1&peak=Mt.+Eolus%2C+Windom+Peak%2C+and+Sunlight+Peak
"},
	{name:"Challenger", surname:"Point", elevation_in_feet:14081, rank:34, location_lat:37.980267, location_long:-105.606766, forest:"Rio Grande", range:"Sangre de Cristo", classification:2.6, exposure:2, elevation_gain_in_feet:5400, round_trip_distance_in_miles:12.5, no_4wd_additional_elevation_in_feet: 0, no_4wd_additional_distance_in_miles:0, route_name:"North Slopes", trailhead_name:"Willow Creek", trailhead_lat:37.98889, trailhead_long:-105.66278, four_x_four_required:1, additional_info_url:"https://www.14ers.com/route.php?route=chal1&peak=Kit+Carson+Peak+and+Challenger+Point
"},
	{name:"Ellingwood", surname:"Point", elevation_in_feet:14042, rank:42, location_lat:37.582508, location_long:-105.492569, forest:"Rio Grande", range:"Sangre de Cristo", classification:2.6, exposure:2, elevation_gain_in_feet:2450, round_trip_distance_in_miles:6, no_4wd_additional_elevation_in_feet: 3750, no_4wd_additional_distance_in_miles:11, route_name:"South Face", trailhead_name:"Lake Como ", trailhead_lat:37.53861, trailhead_long:-105.57611, four_x_four_required:3, additional_info_url:"https://www.14ers.com/route.php?route=elli2&peak=Blanca%2C+Ellingwood+and+Little+Bear
"},
	{name:"North Eolus", surname:"", elevation_in_feet:14039, rank:?, location_lat:37.625416, location_long:-107.620995, forest:"San Juan", range:"San Juan", classification:2.6, exposure:3, elevation_gain_in_feet:3000, round_trip_distance_in_miles:5.2, no_4wd_additional_elevation_in_feet: 3200, no_4wd_additional_distance_in_miles:12, route_name:"South Ridge ", trailhead_name:"Needleton", trailhead_lat:37.63333, trailhead_long:-107.69278, four_x_four_required:TRAIN, additional_info_url:"https://www.14ers.com/route.php?route=neol4&peak=Mt.+Eolus%2C+Windom+Peak%2C+and+Sunlight+Peak"},
]

fourteeners_count = 0
fourteeners_attributes.each do |attributes|
	Fourteener.create!(attributes)
	fourteeners_count += 1
end
puts "created #{fourteeners_count} fourteeners"
